### ISSUE TITLE
props 无法穿透

### ISSUE THREAD

**Issue by Sir0xb** [bytedance/magic-microservices#10]
<custom-component props={{ a: 1, b: 2 }} />
...
magic('custom-component', {
	mount: (container, props) => {
		console.log('mount', props)
		ReactDOM.render(React.createElement(TheComp, props, null), container)
	}
})
mount 无法得到 props 信息

**Comment by jerryOnlyZRJ** [comment]
@Sir0xb 因为受到 web components 官方规范的约束，需要在声明 web components 阶段就声明自定义的 PropTypes，可以参考文档中的说明：https://github.com/bytedance/magic-microservices#props，在执行 magic 函数的时候传入第三个参数 options.propTypes，对于引用类型的数据，请使用 useProps 在使用当前元素时进行包裹
