### ISSUE TITLE
关于 wrapper 样式

### ISSUE THREAD

**Issue by wangcheng007** [bytedance/magic-microservices#24]
wrapper 的样式怎么修改呢，找了下没有相关 API 代码中也是直接写的 width=100% height=100%，能否增加个相关能力

**Comment by ChelesteWang** [comment]
可以尝试直接覆写样式

**Comment by wangcheng007** [comment]
> 可以尝试直接覆写样式

感谢回复，不过感觉这种方式并不好，不是动态传入样式。已 fork 仓库，实现 wrapperStyle API

**Comment by ChelesteWang** [comment]
> > 可以尝试直接覆写样式
> 
> 感谢回复，不过感觉这种方式并不好，不是动态传入样式。已 fork 仓库，实现 wrapperStyle API

欢迎提交 mr 一起完善 magic-microservices
